CREATE TABLE KHACHHANG 
(
	MaKH INT IDENTITY(1,1),
	TenKH NVARCHAR(20),
	MatKhau VARCHAR(20),
	CONSTRAINT pk_MaKH PRIMARY KEY(MaKH)
)

CREATE TABLE SANPHAM
(
	MaSP INT IDENTITY(1,1),
	TenSP NVARCHAR(30),
	ChitietSP NVARCHAR(100),
	LoaiHang NVARCHAR(20),
	Hinh VARCHAR(20),
	Gia FLOAT,
	CONSTRAINT pk_MaSP PRIMARY KEY(MaSP),
	CONSTRAINT fk_LoaiHang FOREIGN KEY (LoaiHang) REFERENCES LOAIHANG(LoaiHang) 
)

CREATE TABLE LOAIHANG
(
	LoaiHang NVARCHAR(20),
	CONSTRAINT pk_LoaiHang PRIMARY KEY (LoaiHang)
)


CREATE TABLE DONHANG
(
	MaDH INT IDENTITY(1,1),
	MaKH INT NOT NULL,
	MaSP INT NOT NULL,
	TongTien FLOAT,
	CONSTRAINT pk_MaDH PRIMARY KEY(MaDH),
	CONSTRAINT fk_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	CONSTRAINT fk_MaSP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
)

--INSERT DATA KHACH HANG--

INSERT INTO KHACHHANG VALUES('vuvanduy','123456');

INSERT INTO KHACHHANG VALUES('vuvanduy2','123456');

INSERT INTO KHACHHANG VALUES('vuvanduy3','123456');

-- INSERT DATA LOAI HANG -- 

INSERT INTO LOAIHANG VALUES('Dien Thoai');

INSERT INTO LOAIHANG VALUES('May Tinh');

INSERT INTO LOAIHANG VALUES('May Tinh Bang');

INSERT INTO LOAIHANG VALUES('Dien Thoai Thong Minh');

-- INSERT DATA SAP PHAM --

INSERT INTO SANPHAM VALUES('Nokia','La dien thoai thong minh' , 'Dien Thoai','',5000000);

INSERT INTO SANPHAM VALUES('SamSung','La dien thoai thong minh' , 'Dien Thoai','',5000000);

INSERT INTO SANPHAM VALUES('Iphone','La dien thoai thong minh' , 'Dien Thoai','',5000000);

INSERT INTO SANPHAM VALUES('DELL','La may tinh thong minh' , 'May Tinh','',5000000);

INSERT INTO SANPHAM VALUES('MAC','La may tinh thong minh' , 'May Tinh','',5000000);

INSERT INTO SANPHAM VALUES('THINKPAD','La may tinh thong minh' , 'May Tinh','',5000000);

